---
- name: Install && Configure PosrtgreSQL
  hosts: db
  become: true
  gather_facts: true
  vars_files:
    - vars.yml

  pre-tasks:
    - name: Install packages postgreSQL
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python3-psycopg2
      tags:
      - postgres

    - name: Install Python packages psycopg2-binary
      pip: "name={{ item }}  state=present"
      with_items:
        - psycopg2-binary
      tags:
      - postgres

  tasks:
    - name: Create app database
      postgresql_db:
        state: present
        name: "{{ db_name }}"
        encoding: UTF-8
        lc_collate: ru_RU.UTF-8
        lc_ctype: ru_RU.UTF-8
        template: template0
      become: true
      become_user: postgres
      tags:
      - postgres

    - name: Create db user
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: true
      become_user: postgres
      tags:
      - postgres

    - name: Grant db user access to app db
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: false
        privs: all
      become: true
      become_user: postgres
      tags:
      - postgres

