---
- name: Enable & start servicer on termidesk-VDI hosts
  hosts: termidesk-vdi
  become: true
  vars_files:
    - vars.yml

  tasks:
  - name: Enable and start termidesk-vdi.service
    ansible.builtin.systemd:
      service: "{{ termidesk_vdi_service }}"
      enabled: true
      state: started