---
- name: Install Termidesk From repo
  hosts: 192.168.18.218
  become: yes
  vars_files:
    - vars.yml

  pre_tasks:
  - name: Add temporary termidesk repository
    ansible.builtin.apt_repository:
      repo: "deb https://termidesk.ru/repos/astra {{ ansible_distribution_release }} non-free"
      state: present
  
  
  - name: Download termidesk repository key
    ansible.builtin.apt_key:
      url: "https://termidesk.ru/repos/astra/GPG-KEY-PUBLIC"
      state: present

  tasks:
  - name: Correct mswitch.conf
    lineinfile:
      path: /etc/parsec/mswitch.conf
      regexp: '^zero_if_notfound'
      line: "zero_if_notfound: yes"


  - name: Install termidesk pkgs
    apt:
      name: "{{ termidesk_pkgs }}"
      state: present
      update_cache: true
    register: termidesk_pkg_installed


  - name: Disable AstraMode in termidesk_apache_conf
    ansible.builtin.lineinfile:
      dest: "{{ termidesk_apache_conf }}"
      regexp: "^AstraMode"
      line: "AstraMode off"
      insertafter: '^# AstraMode on'
      state: present


  - name: restart apache2.service
    ansible.builtin.systemd:
      state: restarted
      name: "{{ termidesk_apache_sevice }}"
      enabled: yes
      
  
  - name: Correct termidesk-taskman.service unit file
    ansible.builtin.lineinfile:
      dest: "/lib/systemd/system/termidesk-taskman.service"
      line: "Restart=on-failure"
      insertafter: '\[Service\]'
      state: present
  
  
  - name: Correct termidesk-wsproxy.service unit file
    ansible.builtin.lineinfile:
      dest: "/lib/systemd/system/termidesk-wsproxy.service"
      regexp: '^(ExecStart=.*)$'
      line: '\1 --host=0.0.0.0 --port=5099'
      backrefs: yes
      state: present


  - name: Reload systemd daemon
    ansible.builtin.systemd:
      daemon_reload: true


  post_tasks:
  - name: Enable and start termidesk-vdi.service
    hosts: termidesk-vdi
    ansible.builtin.systemd:
      service: "{{ termidesk_vdi_service }}"
      enabled: yes
      state: started


  - name: Enable and start termidesk-taskman.service
    hosts: termidesk-taskman
    ansible.builtin.systemd:
      service: "{{ termidesk_taskman_service }}"
      enabled: no
      state: stopped
  

  - name: Enable and start termidesk-wsproxy.service
    hosts: termidesk-wsproxy
    ansible.builtin.systemd:
      service: "{{ termidesk_gateway_sevice }}"
      enabled: yes
      state: started
    
  
  
  
  
  
  
  
  
  
  
  
  
