---
- name: Create VM on ovm.sl.loc
  hosts: localhost
  connection: local
  gather_facts: true
  ignore_unreachable: true
  vars_files: 
    - /home/l1is/Документы/Uveon-git/Uveon-1/Ansible/oVirt/vars.yml

  pre_tasks:
    - name: Login to oVirt
      ovirt.ovirt.ovirt_auth:
        url: "{{ url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
      tags:
      - always

  tasks:
    - name: Creates VM from temp 'ALCE-173-CLI'
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: orel2-12-postgreRaspred03
        description: orel2-12-postgreRaspred03
        template: ALCE-173-CLI
        cluster: Default
        state: present
        


  post_tasks:
    - name: Logout from oVirt
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

  collections:
    - ovirt.ovirt
     