---
- name: Create VM on ovm.sl.loc
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files: /home/l1is/Документы/Uveon-git/Uveon-1/Ansible/oVirt/vars.yaml



  pre_tasks:
    - name: Login to oVirt
      ovirt.ovirt.ovirt_auth:
        url: "{{ ovirt_url }}"
        username: "{{ ovirt_user }}"
        password: "{{ ovirt_password }}"
        
        
      tags:
        - always

  tasks:
    - name: Create new virtal machine from template
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: termidesk_vdi
        template: ALCE-173-GUI
        cluster: Default
        state: running
        wait: yes
      #with_items:
      #- tdsk-vdi2
      #- tdsk-tsk1
      #- tdsk-tsk2
      #- tdsk-db
      #- tdsk-gw1
      #- tdsk-gw2
  
  post_tasks:
    - name: Logout from oVirt
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

  collections:
    - ovirt.ovirt